yatube/about/urls.py
from django.urls import path

from . import views


app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'


urlpatterns = [
    path('search/',  views.search, name='search_results'),
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='edit'),
    path('posts/<int:post_id>/delete/', views.post_delete, name='post_delete'),
    path(
        'posts/<int:post_id>/comments/',
        views.add_comment,
        name='add_comment'
    ),
    path(
        'posts/<int:post_id>/comments/<int:comment_id>/',
        views.comment_delete,
        name='comment_delete'
    ),
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),
]

yatube/yatube/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

handler404 = 'core.views.page_not_found'
handler403 = 'core.views.csrf_failure'
handler500 = 'core.views.internal_server_error'

urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )
    urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),)

yatube/posts/models.py
from django.contrib.auth import get_user_model
from django.db import models

from core.models import CreatedModel

User = get_user_model()


class Group(models.Model):
    """Group model."""
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)
    description = models.TextField()

    class Meta:
        verbose_name = 'Группа'
        verbose_name_plural = 'Группы'

    def __str__(self):
        return self.title


class Post(CreatedModel):
    """Post model."""
    text = models.TextField(
        verbose_name='Текст поста',
        help_text='Текст нового поста',
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts'
    )
    group = models.ForeignKey(
        Group,
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
        related_name='posts',
        verbose_name='Группа',
        help_text='Группа, к которой будет относиться пост',
    )
    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        blank=True
    )

    class Meta:
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'
        ordering = ('-created',)

    def __str__(self):
        return self.text[:15]


class Comment(CreatedModel):
    """Comment model."""
    text = models.TextField(
        verbose_name='Текст комментария',
        help_text='Оставьте свой комментарий'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='comments',
    )
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name='comments'
    )

    class Meta:
        verbose_name = 'Коммент'
        verbose_name_plural = 'Комменты'
        ordering = ('-created',)

    def __str__(self):
        return self.text[:15]


class Follow(models.Model):
    """Follow model."""
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='follower'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='following'
    )

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=['user', 'author'],
                name='unique_follow'
            ),
            models.CheckConstraint(
                check=~models.Q(user=models.F('author')),
                name='not_follow_by_yourself'
            )
        ]
        verbose_name = 'Подписка'
        verbose_name_plural = 'Подписки'

yatube/posts/forms.py
from django import forms

from .models import Comment, Post


class PostForm(forms.ModelForm):
    """Post creation form."""
    class Meta:
        model = Post
        fields = ('text', 'group', 'image')


class CommentForm(forms.ModelForm):
    """Comment creation form."""
    class Meta:
        model = Comment
        fields = ('text',)

yatube/posts/views.py
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.shortcuts import get_object_or_404, redirect, render

from .forms import CommentForm, PostForm
from .models import Comment, Follow, Group, Post, User
from .utils import paginator


def search(request):
    """Search by text and author."""
    if request.method == 'GET':
        query = request.GET.get('q')
        post_list = Post.objects.filter(
            Q(text__icontains=query) | Q(author__username__icontains=query)
        )
        results = all((query, len(post_list) > 0))
        page_obj = paginator(request, post_list)
        context = {
            'query': query,
            'results': results,
            'page_obj': page_obj
        }
        return render(request, 'posts/search_results.html', context)


def index(request):
    """Return the main page."""
    post_list = Post.objects.select_related('author', 'group')
    page_obj = paginator(request, post_list)
    context = {
        'page_obj': page_obj,
    }
    return render(request, 'posts/index.html', context)


def group_posts(request, slug):
    """Return the group page."""
    group = get_object_or_404(Group, slug=slug)
    post_list = group.posts.select_related('author')
    page_obj = paginator(request, post_list)
    context = {
        'group': group,
        'page_obj': page_obj,
    }
    return render(request, 'posts/group_list.html', context)


def profile(request, username):
    """Return the profile page"""
    author = get_object_or_404(User, username=username)
    post_list = author.posts.select_related('author')
    page_obj = paginator(request, post_list)
    user = request.user
    following = (user.is_authenticated and
                 Follow.objects.filter(user=user, author=author))
    context = {
        'author': author,
        'page_obj': page_obj,
        'following': following,
        'user': user,
    }
    return render(request, 'posts/profile.html', context)


def post_detail(request, post_id):
    """Return the post page."""
    post = get_object_or_404(Post, pk=post_id)
    user = request.user
    author = post.author
    form = CommentForm(request.POST or None)
    comments = Comment.objects.filter(post_id=post_id)
    context = {
        'post': post,
        'user': user,
        'author': author,
        'form': form,
        'comments': comments
    }
    return render(request, 'posts/post_detail.html', context)


@login_required
def post_create(request):
    """Return the post creation page."""
    form = PostForm(
        request.POST or None,
        files=request.FILES or None
    )
    if form.is_valid():
        post = form.save(commit=False)
        post.author = request.user
        post.save()
        return redirect('posts:profile', post.author)
    context = {
        'form': form
    }
    return render(request, 'posts/create_post.html', context)


@login_required
def post_edit(request, post_id):
    """Return the post edit page."""
    post = get_object_or_404(Post, pk=post_id)
    user = request.user
    if user != post.author:
        return redirect('posts:post_detail', post_id=post_id)
    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
        instance=post
    )
    if form.is_valid():
        form.save()
        return redirect('posts:post_detail', post_id=post_id)
    context = {
        'form': form,
        'is_edit': True
    }
    return render(request, 'posts/create_post.html', context)


@login_required
def post_delete(request, post_id):
    """Post author deletes his post."""
    post = get_object_or_404(Post, pk=post_id)
    post.delete()
    return redirect('posts:profile', post.author)


@login_required
def add_comment(request, post_id):
    """Adding a comment."""
    post = get_object_or_404(Post, pk=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('posts:post_detail', post_id=post_id)


@login_required
def comment_delete(request, post_id, comment_id):
    """Comment author deletes his comment."""
    comment = get_object_or_404(Comment, id=comment_id)
    comment.delete()
    return redirect('posts:post_detail', comment.post.pk)


@login_required
def follow_index(request):
    """Return the subscription page."""
    user = request.user
    post_list = Post.objects.filter(author__following__user=user)
    page_obj = paginator(request, post_list)
    context = {
        'page_obj': page_obj,
    }
    return render(request, 'posts/follow.html', context)


@login_required
def profile_follow(request, username):
    """Following"""
    author = get_object_or_404(User, username=username)
    user = request.user
    if user != author:
        Follow.objects.get_or_create(
            user=user,
            author=author
        )
    return redirect('posts:profile', username=username)


@login_required
def profile_unfollow(request, username):
    """Unfollowing"""
    author = get_object_or_404(User, username=username)
    user = request.user
    try:
        follow = Follow.objects.get(
            author=author,
            user=user
        )
    except Follow.DoesNotExist:
        follow = None
    follow.delete()
    return redirect('posts:profile', username=username)

yatube/templates/posts/create_post.html
{% extends 'base.html' %}
{% block title %}{% if is_edit %}Редактировать запись{% else %}Создать пост{% endif %}{% endblock %}
{% block content %}
  <div class="container py-5">
    <div class="row justify-content-center">
      <div class="card">
        <div class="card-header">
          {% if is_edit %}
            Редактировать запись
          {% else %}
            Создать пост
          {% endif %}

          {% include 'includes/form_error.html' %}

          <form method="post" enctype="multipart/form-data">
            {% csrf_token %}

            {% for field in form %}
              <div class="form-group row my-3 p-3">
                <label for="{{ field.id_for_label }}">
                  {{ field.label }}
                  {% if field.field.required %}
                    <span class="required text-danger">*</span>
                  {% endif %}
                </label>
                {{ field }}
                {% if field.help_text %}
                  <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                    {{ field.help_text|safe }}
                  </small>
                {% endif %}
              </div>
            {% endfor %}

            <button type="submit" class="btn btn-primary">
              {% if is_edit %}
                Сохранить
              {% else %}
                Добавить
              {% endif %}
            </button>
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

yatube/templates/posts/follow.html
{% extends 'base.html' %}
{% block title %}Подписки{% endblock %}
{% block content %}
    {% include 'posts/includes/switcher.html' %}
    {% for post in page_obj %}
      {% include 'posts/includes/article.html' %}
      {% if not forloop.last %}<hr>{% endif %}
    {% endfor %}
    {% include 'posts/includes/paginator.html' %}
{% endblock %}

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% block title %}Записи сообщества {{ group }}{% endblock %}
{% block content %}
  <div class="container py-5">
    <h1>{{ group }}</h1>
    <p>{{ group.description }}</p>
    {% for post in page_obj %}
      {% include 'posts/includes/article.html' %}
      {% if not forloop.last %}<hr>{% endif %}
    {% endfor %}
    {% include 'posts/includes/paginator.html' %}
  </div>
{% endblock %}

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% block title %}Последние обновления на сайте{% endblock %}
{% block content %}
    <h1>Последние обновления на сайте</h1>
    {% load cache %}
    {% cache 20 index_page with page_obj %}
    {% include 'posts/includes/switcher.html' %}
    {% for post in page_obj %}
      {% include 'posts/includes/article.html' %}
      {% if not forloop.last %}<hr>{% endif %}
    {% endfor %}
    {% endcache %}
    {% include 'posts/includes/paginator.html' %}
{% endblock %}

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}
{% load thumbnail %}
{% load user_filters %}
{% block title %}Пост {{ post.text|truncatewords:30 }}{% endblock %}
{% block content %}
  <div class="row">
    <aside class="col-12 col-md-3">
      <ul class="list-group list-group-flush">
        <li class="list-group-item">
          Дата публикации: {{ post.created|date:"d E Y" }}
        </li>
        {% if post.group %}
          <li class="list-group-item">
            Группа:
            <a href="{% url 'posts:group_list' post.group.slug %}">
              {{ post.group }}
            </a>
          </li>
        {% endif %}
        <li class="list-group-item">
          Автор:
            <a href="{% url 'posts:profile' post.author %}">
              {{ post.author.get_full_name }}
            </a>
        </li>
        <li class="list-group-item d-flex justify-content-between align-items-center">
          Всего постов автора:  <span>{{ post.author.posts.count }}</span>
        </li>
        <li class="list-group-item">
          <a href="{% url 'posts:profile' post.author %}">
            все посты пользователя
          </a>
        </li>
      </ul>
    </aside>
    <article class="col-12 col-md-9">
      {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
        <img class="card-img my-2" src="{{ im.url }}">
      {% endthumbnail %}
      <p>
        {{ post.text|linebreaks }}
      </p>

      {% if user == author %}
        <a class="btn btn-default" href="{% url 'posts:edit' post.pk %}">
          <span class="glyphicon glyphicon-pencil"></span>
          Редактировать пост
        </a>
        <a class="btn btn-default" href="{% url 'posts:post_delete' post.pk %}"
           type="submit" onclick="return confirm('Вы уверены?')">
          <span class="glyphicon glyphicon-pencil"></span>
          Удалить пост
        </a>
      {% endif %}

        {% if user.is_authenticated %}
            <div class="card my-4">
            <h5 class="card-header">Добавить комментарий:</h5>
            <div class="card-body">
                <form method="post" action="{% url 'posts:add_comment' post.id %}">
                    {% csrf_token %}
                    <div class="form-group mb-2">
                        {{ form.text|addclass:"form-control" }}
                    </div>
                    <button type="submit" class="btn btn-primary">Отправить</button>
                </form>
            </div>
        </div>
        {% endif %}

        {% for comment in comments %}
            <div class="media mb-4">
                <div class="media-body">
                    <h5 class="mt-0">
                    <a href="{% url 'posts:profile' comment.author.username %}">
                        {{ comment.author.username }}
                    </a>
                    </h5>
                    <p>
                        {{ comment.text }}
                    </p>
                </div>
            </div>

            {% if user == comment.author %}
              <a class="btn btn-default" href="{% url 'posts:comment_delete' post.pk comment.id %}"
                  type="submit" onclick="return confirm('Вы уверены?')">
                <span class="glyphicon glyphicon-pencil"></span>
                Удалить комментарий
              </a>
            {% endif %}
        {% endfor %}

    </article>
  </div>
{% endblock %}

yatube/templates/posts/profile.html
{% extends 'base.html' %}
{% block title %}Профайл пользователя {{ author }}{% endblock %}
{% block content %}
  <div class="mb-5">
    <h1>Все посты пользователя {{ author }}</h1>
    <h3>Всего постов: {{ author.posts.count }}</h3>

    {% if user != author %}
      {% if following %}
        <a
          class="btn btn-lg btn-light"
          href="{% url 'posts:profile_unfollow' author.username %}" role="button"
        >
          Отписаться
        </a>
      {% else %}
        <a
          class="btn btn-lg btn-primary"
          href="{% url 'posts:profile_follow' author.username %}" role="button"
        >
          Подписаться
        </a>
      {% endif %}
    {% endif %}

    <p>
      <h5>Подписчиков: {{ author.following.count }}</h5>
    </p>

    {% for post in page_obj %}
      {% include 'posts/includes/article.html' %}
      {% if not forloop.last %}<hr>{% endif %}
    {% endfor %}

    {% include 'posts/includes/paginator.html' %}
  </div>
{% endblock content %}

yatube/templates/posts/search_results.html
{% extends 'base.html' %}
{% block title %}Результаты поиска{% endblock %}
{% block content %}
    <h1>{{ query }}: Результаты поиска</h1>
    {% if results %}
        {% for post in page_obj %}
            {% include 'posts/includes/article.html' %}
            {% if not forloop.last %}<hr>{% endif %}
        {% endfor %}
        {% include 'posts/includes/paginator.html' %}
    {% else %}
        <p>Ничего не найдено:(</p>
    {% endif %}
{% endblock %}